# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

development:
  <<: *default
  database: rails_test_development

test:
  <<: *default
  database: rails_test_test

production:
  primary:
    <<: *default
    database: rails_test_production
  cache:
    <<: *default
    database: rails_test_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: rails_test_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: rails_test_production_cable
    migrations_paths: db/cable_migrate
